apiVersion: v1
kind: Pod
metadata:
  name: contacts
  namespace: default
spec:
  containers:
  - name: contacts
    image: localhost:5000/contacts
    ports:
    - containerPort: 3000
    env:
    - name: MONGO_URL
      value: mongodb://mongo:27017/ejercicio4
---
apiVersion: v1
kind: Service
metadata:
  name: contacts-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 32200
  selector:
    app: contacts